[package]
name = "kish"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.6.0"

[[bench]]
name = "ir_throughput"
harness = false
